### ISSUE TITLE
how to pass the variable

### ISSUE THREAD

**Issue by NorbertoAlcantara** [jonathan-dejong/acf-form-shortcode#5]
I need to pass the logged in user ID.

how to make?

**Comment by jonathan-dejong** [comment]
Hi @NorbertoAlcantara 

The shortcode is 100% just a wrapper for ACF_Form. 
So you can see what can be passed into the function here:
https://www.advancedcustomfields.com/resources/acf_form/

I don't know what you mean otherwise. You can add your own input with html_before_field or html_after_field (and there are ACF hooks to use) to have it submit along with the rest of the fields. 
Or you can create a hidden field in your ACF field group and prefill it in the frontend with your user ID using ACFs hooks. 

Regardless this plugin is simply a wrapper for acf_form to allow people to easily add a form to an editor in admin. :)
